server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: POPOLNET
    url: jdbc:mysql://13.125.125.240:3306/POPOLNET
    username: POPOLNET

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


