server:
  servlet:
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  expiration-hours: 3
  issuer: hd0001

springdoc:
  packages-to-scan: com.project.portnet_be.application
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui/
    show-actuator: true
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
